### ISSUE TITLE
hydrogenbond analysis notebook

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/UserGuide#105]
**Is your feature request related to a problem? Please describe.**

HydrogenBondAnalysis is one of the most used features. We recently deprecated the old approach and in 2.0.0 there will only be https://docs.mdanalysis.org/2.0.0-dev0/documentation_pages/analysis/hydrogenbonds.html. The analysis is often not straightforward and the docs are concise but not enough for someone new to MDAnalysis.

**Describe the solution you'd like**
I'd like to see a notebook that shows
- basic H-bond analysis (running, parsing output) (e.g. solvent)
- intermediate (between protein and drug, non-standard donors/acceptors)

**Describe alternatives you've considered**
Asking questions on the mailing list... but it would safe everybody time if we could direct people to a notebook in the UG.

**Comment by orbeckst** [comment]
@bieniekmateusz @p-j-smith would you be able to have a go at writing a H-bond analysis tutorial?

**Comment by p-j-smith** [comment]
Yeah sure, I should have some time this week to write a tutorial. For the intermediate-level analysis, so that I don't add another system to the datafiles unnecessarily, do you know if any of the current tpr or psf files in `testsuite/Mdanalysis/data` are of a protein and drug?

**Comment by orbeckst** [comment]
Not sure, maybe @IAlibay @RMeli might know?

We could also add something to MDAnalysisData if someone has a suitable system. Would be very useful.

**Comment by RMeli** [comment]
Unfortunately I don't know on top of my mind, but would be interested to find out as well. If a new trajectory needs to be added, a system with a highly symmetric ligand would be ideal for future work. =)

**Comment by IAlibay** [comment]
Off the top of my head, I don't think we do, but I'll have a thorough look through once I get back to work tomorrow.

If needed probably have some protein-ligand simulations that could be added to MDAnalysisData. I'm thinking some of the more classic T4 lysozyme (e.g. 2RBN) or BRD4 case studies (e.g. Bromosporine) could be appropriate?

**Comment by orbeckst** [comment]
That sounds perfect. 

Oliver

**Comment by IAlibay** [comment]
I couldn't find anything in either the MDA test set or MDAnalysisData, so I've created an issue in MDAnalysisData to discuss this.

**Comment by orbeckst** [comment]
See also recent thread https://groups.google.com/g/mdnalysis-discussion/c/p1Q6GZuqlEg

**Comment by lilyminium** [comment]
Closed by #133
