### ISSUE TITLE
build and publish the user guide

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/UserGuide#12]
Add travis CI to automatically build the user guide. 

See [MDAnalysisTutorial/.travis.yml](https://github.com/MDAnalysis/MDAnalysisTutorial/blob/master/.travis.yml).

- [x] add to Travis (@orbeckst or @richardjgowers )
- [x] encrypt token (@orbeckst can do it)
- [x] add a modified `.travis.yml`

The user guide should then show up as https://www.mdanalysis.org/UserGuide.

**Comment by orbeckst** [comment]
https://travis-ci.com/MDAnalysis/UserGuide exists and is ready (I think...)

**Comment by orbeckst** [comment]
Notes on deploying docs and token: https://docs.travis-ci.com/user/deployment/pages/

**Comment by orbeckst** [comment]
I [encrypted the access token](https://docs.travis-ci.com/user/environment-variables#defining-encrypted-variables-in-travisyml) with
```bash
travis encrypt GH_TOKEN=super-secret-gobbledy-gook
```
and got
```yaml
  secure: "b+s7g/GarZTFQjnLuC4gRFuf/V+FNu2ml+Sdo9qQgVZdHFC2sJPNWqszd2KssRplpwe5d/zhPAj0tiQWreNRt0VdPCJpImeEp7hfxLtHsMrGfBGDFuBKi+XK6LqNnCqYeneWE3Q6Gb3EFqCwYEw75Tph1HIkc0jj4h2CvX+SYzeUopcj2HiZXEJhcUPQFDnawHEz1WkZcmK4TMumesE4+OOq+sDg0aWpVzo0hA0Pu0h9FTipeExKI9WngkCdgWmuTWsTyqOfhyXQKcs0Q+X1ycmbHidic2SWc1Tsyg0jdWvdAPN2KGcS4J9EdhtTaJARYdizVTlR8SS6VjbDPIDSHxXli4dSFGdVMSADqu6jCeDfcyTpjc5/iB1g4k77Hmmxehj4n+63fg7Ja+cFGPYu/337ZVQAKU9C7N/dFinZaBWFkEA9VbSHJogDi5v1wtwE1MoLZKNn73zM4OlnWm8bJNk7PKgQ/YPM+Fmp/Bb5K8JLH6aF1jSReXvYTp7PZaZwJ/bW0xdUGCOAW3Z9ieBVJAPSwzPe1GXjXAzUUbwXMxEiITDFO4VigkViDSSbAnOoMeR0l7tFMwsNgB7nrDWPvHufkc2dQOs6LmOVGA6v8rK/xxrj5eau947w0m6bNq3qWGxUwjm//hoWcNJqIYWnFPKwf7ELtipYm3ifywPidKc="
```
@lilyminium add the "secure: ..." line to `.travis.yml`. 

It will expand to `GH_TOKEN=...` so that the deploy script in the travis config can use it to push to the gh-pages branch.

**Comment by orbeckst** [comment]
Note that the `.travis.yml` file installs the sphinx-sitemap package. You should import it in your config file so that everything is indexed for the algolia search. See https://github.com/MDAnalysis/MDAnalysis.github.io/issues/78

**Comment by lilyminium** [comment]
Thanks @orbeckst . I'll see if I can get the build to stop failing soon...

**Comment by orbeckst** [comment]
I think you have to also install pandoc. You can either switch to a conda installation (takes longer but almost certainly has all packages) or install pandoc as an Ubuntu package (see [Travis installing deps](https://docs.travis-ci.com/user/installing-dependencies/)) and any other Python packages via `pip`. 

Btw, might be useful to add the Travis build status badge to the README for quick link to the builds.

**Comment by orbeckst** [comment]
Btw, I am not 100% sure if the GH_TOKEN is working at the moment because it does not show up as a proper `export GH_TOKEN=[secure]` in the log. Instead it looks like `export RANDOM_STRING_WHICH_IS_LUCKILY_NOT_THE_TOKEN=[secret]`. I might have to encrypt with a newer version of the `travis` tool.

Just in case you get it to working but the push fails.

**Comment by lilyminium** [comment]
Thanks! Unfortunately that does seem to have happened.

```
$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.10.13
1 gem installed
invalid option "--github_token="
failed to deploy
```

**Comment by orbeckst** [comment]
I’ll look into the token issue.

**Comment by orbeckst** [comment]
https://www.mdanalysis.org/UserGuide/ – yay !

I needed to 
```
travis login --pro
travis encrypt --pro "GH_TOKEN='[secret]'"
```
because we are on travis-ci.com ... just needed to read their docs properly!

**Comment by orbeckst** [comment]
Do you want to email the new url to the list and ask for feedback?
