### ISSUE TITLE
License for the user guide

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/UserGuide#134]
So I might not be looking at the right place, but as far as I can tell the user guide doesn't directly declare any type of license.

I guess the assumption is that it inherits MDA's GPLv2 license?

Given that the user guide is a really good teaching resource, I think it might be good to make it clear as to what the license is so that folks can be more confident in using parts of it in derivative works where possible.

**Comment by RMeli** [comment]
Given that it is more text than code, it is worth thinking about a CC license as well?

**Comment by jbarnoud** [comment]
I think a CC license would be the most appropriate. However, the user guide is backed quite a bit by docstring and those have been contributed under GPL. That may be an issue.

**Comment by IAlibay** [comment]
Ideally a CC-BY4 license would be most appropriate, but I agree with @jbarnoud if anything in the userguide is taken out of the docs verbatum we'd probably have to adhere to GPL. @lilyminium might have a better view of things here, but maybe it's one of those we should be asking the numfocus folks?

**Comment by RMeli** [comment]
I was thinking more about a dual license model that I've seen multiple times in this scenario: CC for text and GPL for code? CC-BY-SA is reasonably aligned with GPL (I think). 

Of course if you have access to NumFocus advice, they will probably know already how to handle this.

**Comment by lilyminium** [comment]
> I was thinking more about a dual license model that I've seen multiple times in this scenario: CC for text and GPL for code? CC-BY-SA is reasonably aligned with GPL (I think).

If we can do that then that sounds like the best solution to me

**Comment by hmacdope** [comment]
Sounds good.
