### ISSUE TITLE
Update testing

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#166]
Right now testing is on 3.7 or 3.8 because I'm lazy, but it should really run on all the Python versions supported by MDA to check the notebooks.

**Comment by ojeda-e** [comment]
Can I help with this @lilyminium? I'm willing to give CI a second chance. 😅

**Comment by IAlibay** [comment]
@lilyminium I've taken the stance here that "it should work across multiple python versions" really is a problem with the core library. The assumption we should always take downstream is that if the minimum allowed Python version works then anything else should.

Now that py3.8 is the minimum version, would we be ok instead just taking the stance that the minimum version we build on is the minimum allowed version by MDA?

**Comment by lilyminium** [comment]
Maybe minimum and maximum? It would be handy to be able to build locally without too many restrictions.

**Comment by IAlibay** [comment]
> Maybe minimum and maximum? It would be handy to be able to build locally without too many restrictions.

I'm not sure I understand why maximum would be required? Python 3.6+ is backwards compatible so if it works with py3.8 then it should also work with py3.11? Are we expecting that there might be a library that doesn't work in that way?

**Comment by lilyminium** [comment]
Yeah, it's the dependencies I'm thinking of.

**Comment by lilyminium** [comment]
Closing as this is no longer desired (see #276).

**Comment by jandom** [comment]
Thanks for closing @lilyminium – otherwise the ticket would stay open and potentially attract other courageous contributors ;P
