### ISSUE TITLE
sitemap.xml contains only broken links

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/UserGuide#172]
**Describe the bug**
The https://userguide.mdanalysis.org/2.0.0/sitemap.xml only contains broken links because **a slash is missing after the hostname**, for instance
```xml
<?xml version='1.0' encoding='utf-8'?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url><loc>https://userguide.mdanalysis.orgadvanced_topology.html</loc></url>
<url><loc>https://userguide.mdanalysis.orgatomgroup.html</loc></url>
<url><loc>https://userguide.mdanalysis.orgcontributing.html</loc></url>
...
```

**To Reproduce**
1. Go to https://userguide.mdanalysis.org/2.0.0/sitemap.xml
2. look at file

**Expected behavior**
Links should link to actual pages

**Actual behavior**
Links are incomplete and thus broken.

Therefore, pages are not indexed for search.

**Additional context**
See also https://github.com/MDAnalysis/MDAnalysis.github.io/issues/202

**Comment by orbeckst** [comment]
I just check https://userguide.mdanalysis.org/stable/sitemap.xml and https://userguide.mdanalysis.org/2.0.0/sitemap.xml and they are still missing forward slashes after the hostname. Can you please check?

**Comment by jandom** [comment]
Eh, this still looks busted to me https://userguide.mdanalysis.org/stable/sitemap.xml

**Comment by lilyminium** [comment]
Ah, this should get manually fixed, yes. Any recent changes to the repo will only affect the development versions unless we re-trigger building of previous docs. The develop sitemap looks better: https://userguide.mdanalysis.org/dev/sitemap.xml

**Comment by jandom** [comment]
Ah, okay – nevermind then!

**Comment by lilyminium** [comment]
I updated `gh-pages` manually for old releases -- https://userguide.mdanalysis.org/stable/sitemap.xml looks good now :)
