### ISSUE TITLE
Fix typos in the user guide - multiple PRs welcome!

### ISSUE THREAD

**Issue by micaela-matta** [MDAnalysis/UserGuide#194]
This issue is designed to be incrementally achieved through multiple PRs. 

There are a few typos in the user guide, this issue will collect as many as we can find starting with the short list below.
Feel free to fix any typos/formatting errors we haven't noticed and add them in the comments!

- units and conversions [page]( https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/units.html?highlight=unit%20conversion#conversions), note box: "in the future me might" 
- units and conversions [page]( https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/units.html?highlight=unit%20conversion#conversions), above the note box: fix LaTeX formatting for `rho/rho0 = n/(N_A * M**-1) / rho0 where [n] = 1/Volume, [rho] = mass/Volume`
- units and conversions [page]( https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/units.html?highlight=unit%20conversion#conversions), `MDAnalysis.units.water`: fix scientific notation in`and molar mass 18.016 g mol**-1`
- density analysis [page](https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/analysis/density.html), units and conversions [page]https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/units.html?highlight=unit%20conversion#conversions) (and probably many other pages): the symbol `Å`  appears many times in different formats (`ångströms`, `Å**-3`, `Angstroms` etc). Depending on the context in the page, keep LaTeX equation style or replace with the standard symbol `Å` and correct scientific notation.

**Comment by lilyminium** [comment]
Sorry, all of these typos should be fixed in the core MDAnalysis/mdanalysis repo!
