### ISSUE TITLE
Issue with installation of User Guide

### ISSUE THREAD

**Issue by thinkbeyondit83** [MDAnalysis/UserGuide#204]
Unable to run sphinx build command ->
code trying to run: python -m sphinx_autobuild source build
show the full error output:
Error log:
Traceback (most recent call last):
  File "/home/dhairya/Desktop/UserGuide/doc/source/scripts/gen_format_overview_classes.py", line 112, in <module>
    ov = FormatOverview()
  File "/home/dhairya/Desktop/UserGuide/doc/source/scripts/base.py", line 36, in __init__
    self.get_lines(*args, **kwargs)
  File "/home/dhairya/Desktop/UserGuide/doc/source/scripts/base.py", line 54, in get_lines
    lines.append(self.get_line(*items))
  File "/home/dhairya/Desktop/UserGuide/doc/source/scripts/base.py", line 66, in get_line
    line.append(self._run_method(h, *args))
  File "/home/dhairya/Desktop/UserGuide/doc/source/scripts/base.py", line 42, in _run_method
    val = meth(*args, **kwargs)
  File "/home/dhairya/Desktop/UserGuide/doc/source/scripts/gen_format_overview_classes.py", line 55, in _description
    return DESCRIPTIONS[self.keys[-1]]
KeyError: 'H5MD'
Wrote  formats/selection_exporter_formats.txt
Wrote  generated/selections/protein.txt
Wrote  generated/selections/protein_backbone.txt
Wrote  generated/selections/nucleic.txt
Wrote  generated/selections/nucleic_backbone.txt
Wrote  generated/selections/base.txt
Wrote  generated/selections/nucleic_sugar.txt
Wrote  generated/topology/groupmethods.txt
Wrote  generated/topology/defaults.txt
Traceback (most recent call last):
  File "/home/dhairya/Desktop/UserGuide/doc/source/scripts/gen_topologyparser_attrs.py", line 28, in <module>
    from MDAnalysisTests.topology.test_parmed import BaseTestParmedParser
ModuleNotFoundError: No module named 'MDAnalysisTests.topology.test_parmed'
Wrote  generated/units_table.txt
WARNING: while setting up extension sphinx.addnodes: node class 'meta' is already registered, its visitors will be overridden
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
intersphinx inventory has moved: https://docs.scipy.org/doc/numpy/objects.inv -> https://numpy.org/doc/stable/objects.inv
loading intersphinx inventory from https://docs.mdanalysis.org/2.2.0-dev0/objects.inv...
loading intersphinx inventory from https://docs.pytest.org/en/latest/objects.inv...
loading intersphinx inventory from https://chemfiles.org/chemfiles.py/latest/objects.inv...
loading intersphinx inventory from http://parmed.github.io/ParmEd/html/objects.inv...
intersphinx inventory has moved: http://parmed.github.io/ParmEd/html/objects.inv -> https://parmed.github.io/ParmEd/html/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 114 source files that are out of date
updating environment: [new config] 114 added, 0 changed, 0 removed

pwd: /home/dhairya/Desktop/UserGuide/doc

**Comment by orbeckst** [comment]
I think you need to do a full stack installation in your build environment — parmed, h5py etc are packages that might not be installed by default. 

Have you followed https://userguide.mdanalysis.org/stable/contributing_docs.html#creating-a-development-environment for setting up the environment?

**Comment by jandom** [comment]
Could we close due to inactivity?

**Comment by jandom** [comment]
@lilyminium what do you think? no response since my last comment, can we wrap it up? active tickets = better visibility

**Comment by IAlibay** [comment]
Closing due to lack of information, please reopen if necessary.
