### ISSUE TITLE
Changes made in dependecy list for smooth installation

### ISSUE THREAD

**Issue by aditi2906** [MDAnalysis/UserGuide#205]
There are a few suggested changes in the installation requirements of MDanalysis UserGuide to make it beginner-friendly.
After cloning the repo and creating a virtual environment:
a)Extracting dependency list from environment.yml to requirments.txt
b)Removing python dependency present in requirments.txt
c)resolving conflict between two different versions of jinja2 (accepting jinja2<3.1)
d)running pip install wheel
e)pip install markup 2.0.1

The above changes helped me install and run UserGuide smoothly on my local machine.

System: Ubuntu 20.04.4 LTS
installing using: pip

**Comment by jandom** [comment]
Maybe we can close this one out? It's nearly a year old and there was a [merged PR](https://github.com/MDAnalysis/UserGuide/pull/229) that potentially fixed it?
