### ISSUE TITLE
Remove generated text files

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/UserGuide#207]
Follow-up from #203 

There are generated text files on the main branch that probably shouldn't be there? We probably should remove them.

**Comment by jandom** [comment]
Seems like these have been all removed through https://github.com/MDAnalysis/UserGuide/pull/278/files – on development the `doc/source/generated/` has been removed. Maybe we can close this one out?

**Comment by lilyminium** [comment]
Thanks for noticing @jandom -- closing.
