### ISSUE TITLE
Document linting with darker

### ISSUE THREAD

**Issue by pgbarletta** [MDAnalysis/UserGuide#247]
Darker linting was added in [this PR](https://github.com/MDAnalysis/mdanalysis/pull/3954).

I think this is pretty much the information a developer needs:

Install:
```
conda install -c conda-forge darker flake8
````
Usage (assuming we forked from `develop` branch):
```
darker --check --diff --color -r upstream/develop -L flake8  package/MDAnalysis
darker --check --diff --color -r upstream/develop -L flake8  testsuite/MDAnalysisTests
```

**Comment by IAlibay** [comment]
Linting is, in my opinion, a very personal thing. We added darker because we got tired of writing comments about pep8, but I'm not sure it would be where I would point folks to necessarily?

I generally just tell folks to use whatever works with their IDE as long as they only fix things in the stuff they touch.

**Comment by pgbarletta** [comment]
but it would still be a useful addition, right? Like "...This is not essential, but if you want your darker action to pass, here's how to check your code against it..."

**Comment by IAlibay** [comment]
I think I'll let the other @MDAnalysis/coredevs chime in here - I personally don't know to what extent I really want to recommend `black` (indeed I use darker as a very loose guide since I dislike how it formats lists and dictionaries).

**Comment by jbarnoud** [comment]
My assumption is that our use of darker is some sort of trial for now. I don't really know what it will recommend and to what extent I am going to agree with it.

With that in mind, it may indeed be useful to point people to the method to run the tool on their PR. It is frustrating to have to push to see the result of the CI and being able to run the tool locally can save some frustration. So :+1: for documenting our use of darker, but with warnings and caveats around the doc.
