### ISSUE TITLE
[DEPLOYMENT] Size of artifacts deployed too large causing timeouts

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/UserGuide#255]
We're deploying 8.4 GB of artifacts when trying to deploy, that's causing the deployment action to timeout (rightfully).

We need to find a proper solution to this problem.

**Comment by IAlibay** [comment]
For context, that's 8.4 times higher than the github pages limit of 1GB! https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits

**Comment by IAlibay** [comment]
related to #218

**Comment by IAlibay** [comment]
The biggest offender seems to be: ./examples/analysis/alignment_and_rms/

Combined this accounts for ~ 270/400 MB of each version we publish.

**Comment by IAlibay** [comment]
As a stopgap I've deleted a couple of old dev versions, that's brought us down to just under 8 GB.

So here are some more actions we could do:
- [ ] Delete old releases from the gh-pages branch, possibly anything before 2.0 as a minimum?
- [ ] Work out what's using up so much space in the examples and remove them.

**Comment by orbeckst** [comment]
Oops... I would just advocate for keeping the last 1.x docs also online.

**Comment by IAlibay** [comment]
> Oops... I would just advocate for keeping the last 1.x docs also online.

There's only really 3 1.x releases, so the maximum savings aren't that great either way.

So the main issues here are actually down to a bunch of leftover widget state data being stored in the notebook metadata (with entire PDB files!). If someone is feeling brave we could manually cut out that data from the old notebook versions  / generated html. That's a pretty big job though.

**Comment by orbeckst** [comment]
Is there a simple `find` command (or similar) that identifies culprits so that we can generate a list of notebooks to look at and edit?

Do we need to change the history to trim the repository size?

**Comment by lilyminium** [comment]
This is the downside of nglview, embedding the interactive widgets is the cause of the expensive PDB storage. We could replace with images and that would cut down 90% of it I think.

**Comment by orbeckst** [comment]
Static images or animated gifs?

**Comment by lilyminium** [comment]
Can definitely do gifs!On Jun 7, 2023, at 03:24, Oliver Beckstein ***@***.***> wrote:﻿
Static images or animated gifs?

**Comment by IAlibay** [comment]
Is someone willing to take ownership of this task?

**Comment by lilyminium** [comment]
I can do this, just might take a couple days On Jun 7, 2023, at 08:13, Irfan Alibay ***@***.***> wrote:﻿
Is someone willing to take ownership of this task?

**Comment by IAlibay** [comment]
> I can do this, just might take a couple days On Jun 7, 2023, at 08:13, Irfan Alibay ***@***.***> wrote:﻿
> Is someone willing to take ownership of this task?
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

I managed to reduce the size just enough to get 2.5.0, so I guess there's a bit of extra time on this now.

**Comment by IAlibay** [comment]
Any updates on this? We're slowly creeping towards the next scheduled release.

**Comment by lilyminium** [comment]
Working on it now. I'm having trouble using the NGLView Moviemaker to create gifs -- if anyone has an environment where it works, it'd be great to see if I can copy the versions.
