### ISSUE TITLE
Broken link to AutoDock specs for PDBQT

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/UserGuide#259]
The PDBQT specification contains a broken link to AutoDock "What is the format of a PDBQT file".

https://autodock.scripps.edu/faqs-help/faq/what-is-the-format-of-a-pdbqt-file

**Comment by pgbarletta** [comment]
Apparently they're redoing the site. For now, [this PDF](https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/AutoDock4.2.6_UserGuide.pdf) seems to be the only available replacement:



I can replace the link with the PDF on the user guide and the [docs](https://docs.mdanalysis.org/1.0.1/documentation_pages/coordinates/PDBQT.html)
