### ISSUE TITLE
CI tests are failing

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/UserGuide#262]
See: https://github.com/MDAnalysis/UserGuide/actions/runs/5515357882/jobs/10055602253

**Comment by IAlibay** [comment]
Can we get a volunteer from @MDAnalysis/coredevs please?

**Comment by jandom** [comment]
This looks pretty simple, it seems like there was some minor drift relative to the reference outputs? Would a valid solution be just updating the reference values to match the new output?

**Comment by orbeckst** [comment]
## FAILED pca.ipynb::Cell 15

I think changing the reference will be ok for the numerical test with the sine content
```
assert reference_output == test_output failed:

  'Cosine conte...C 3 = 0.724\n' == 'Cosine conte...C 3 = 0.723\n'
  Skipping 52 identical leading characters in diff, use -v to show
  - C 2 = 0.906
  ?           ^
  + C 2 = 0.905
  ?           ^
  - Cosine content for PC 3 = 0.723
  ?                               ^
  + Cosine content for PC 3 = 0.724
  ?                               ^
```
The other two need looking into: 

## FAILED hbonds-lifetimes.ipynb::Cell 15

Not even sure what's happening here so one needs to run it and manually check:
```
Notebook cell execution failed
Cell 20: Cell outputs differ

Input:
mean_xy_area = np.mean(
    [np.product(ts.dimensions[:2]) for ts in u.trajectory[hbonds.frames]]
)
counts /= mean_xy_area


Traceback:
Unexpected output fields from running code: {'stderr'}
```

## FAILED hbonds.ipynb::Cell 20
This one seems to have changed the output order (?) — I suppose we could change the reference or somehow make it more robust??
```
  assert reference_output == test_output failed:

  'ARG-71-NH2\t...1\tcount=92\n' == 'ARG-71-NH2\t...1\tcount=92\n'
  Skipping 98 identical leading characters in diff, use -v to show
  Skipping 181 identical trailing characters in diff, use -v to show
    count=96
  - TYR-24-OH	HH	GLY-214-OT2	count=95
  - THR-199-OG1	HG1	ASP-197-OD1	count=95
  + THR-199-OG1	HG1	ASP-197-OD1	count=95
  ?            	   	           	        +
  + TYR-24-OH	HH	GLY-214-OT2	count=95
```

**Comment by IAlibay** [comment]
Ideally making this more robust would be great, but I'm also ok with a temporary fix to just keep things going.

**Comment by jandom** [comment]
Has anyone been able to build this on Mac M1? Please stop me if it's a trigger question, i'm happy to just eject into docker and never think about it. 

When trying to repro, I just ran what the CI runs, ie

> micromamba create -n guide -y --log-level warning python==3.9 hole2 pip -f environment.yml

But that errors with 

```
error    libmamba Could not solve for environment specs
    Encountered problems while solving:
      - nothing provides requested hole2
```

Sure, let's remove hole2 from the requirements

> micromamba create -n guide -y --log-level warning python==3.9 pip -f environment.yml

But then when running pytest, i'm immediately throw into build joys with this ImportError

```

Traceback:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/micromamba/envs/guide/lib/python3.9/site-packages/MDAnalysis/lib/util.py:220
    219 try:
--> 220     from ._cutil import unique_int_1d
    221 except ImportError:

ImportError: dlopen(/Users/jandom/micromamba/envs/guide/lib/python3.9/site-packages/MDAnalysis/lib/_cutil.cpython-39-darwin.so, 0x0002): tried: '/Users/jandom/micromamba/envs/guide/lib/python3.9/site-packages/MDAnalysis/lib/_cutil.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jandom/micromamba/envs/guide/lib/python3.9/site-packages/MDAnalysis/lib/_cutil.cpython-39-darwin.so' (no such file), '/Users/jandom/micromamba/envs/guide/lib/python3.9/site-packages/MDAnalysis/lib/_cutil.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by orbeckst** [comment]
We have osx arm64 conda packages for MDA — that's fully supported, see https://anaconda.org/conda-forge/mdanalysis/files . I don't have an M1/2 mac here to test but a few other people do  (ping @lilyminium @ianmkenney , can you please check, given that you have such machines specifically for testing compatibility?)

**Comment by lilyminium** [comment]
Yes, I can run pytest:

```bash
micromamba env create -f environment.yml
micromamba activate mda-user-guide
cd tests
pytest
```

I did add `moviepy` and `imageio` to the environment file due to various NGLView issues, but otherwise no changes to the environment.

I do wind up with Python 3.9 without specifying it -- possibly another pin in the env file does it!

**Comment by lilyminium** [comment]
> Unexpected output fields from running code: {'stderr'}

This is a numpy warning, I think:

```
/var/folders/bf/2ytrzlmd6jbbgqs37bl9lld40000gn/T/ipykernel_76778/236676029.py:2: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  [np.product(ts.dimensions[:2]) for ts in u.trajectory[hbonds.frames]]

```
