### ISSUE TITLE
Tutorial notebook wishlist

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#29]
Ongoing list of notebooks to make:

- [x] Alignments
- [x] RMSD/F
- [x] PCA
- [x] Creating a custom TopologyAttr
- [x] Helix analysis (#126)
- [x] Hydrogen bonds (#105)

**Comment by orbeckst** [comment]
I'd call this a whish-list and possibly something where other people can also contribute.

**Comment by lilyminium** [comment]
Closed by #126 and #133. Future notebook wishlists should be a new issue.
