### ISSUE TITLE
Dev builds using the new theme don't link to the old versions

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/UserGuide#311]
**Describe the bug**
At least on mobile I can't see the links to the old versions when I access: https://userguide.mdanalysis.org/dev/

**To Reproduce**
Go to https://userguide.mdanalysis.org/dev/ and click on the version selector at the bottom left.

**Expected behavior**
I should be able to see historical doc builds.

Device: Android  Chrome browser (desktop mode).

**Comment by IAlibay** [comment]
Seeing the same issue on the core library docs.

**Comment by lilyminium** [comment]
This appears to be true for all dev docs, e.g. https://userguide.mdanalysis.org/2.7.0-dev0/
