### ISSUE TITLE
Document chainID attribute on PDBQTParser

### ISSUE THREAD

**Issue by pgbarletta** [MDAnalysis/UserGuide#319]
PDBQTParser now parses `chainID`, since [PR#4284](https://github.com/MDAnalysis/mdanalysis/pull/4284).

Sites where this will impact:

 * https://userguide.mdanalysis.org/stable/formats/index.html
 * https://userguide.mdanalysis.org/stable/topology_system.html
 * https://userguide.mdanalysis.org/stable/formats/topology.html
 * https://userguide.mdanalysis.org/stable/formats/reference/pdbqt.html

Curiously, the last one says that `chainID` is both parsed and written, which wasn't true before. It's also the only site that was hand-written, so that explains it.

I'll do it (I can't assign people, so I can't assign myself).

**Comment by lilyminium** [comment]
Thanks @pgbarletta! I think for the autogenerated docs, they should have already updated. Could you please check the `dev` versions of those links please? https://userguide.mdanalysis.org/dev/formats/index.html

**Comment by pgbarletta** [comment]
Oh, right. I was checking those on my local install which had an outdated version of MDA.
