### ISSUE TITLE
2.7.0 release

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/UserGuide#350]
Now that MDA 2.7.0 is out, a 2.7.0 release of the userguide should be made.

**Comment by IAlibay** [comment]
Likely depends on #362 being dealt with first.

**Comment by IAlibay** [comment]
@RMeli @lilyminium a gentle reminder that this still needs to be done. I've done more or less all the other fixes, so as far as I can tell, assuming things still deploy but just not consistently, all that's needed here is a tag push.

**Comment by RMeli** [comment]
Looks like 2.7.0 deployed successfully: https://userguide.mdanalysis.org/2.7.0/

Thanks @IAlibay for the reminder and fixes!

**Comment by IAlibay** [comment]
@RMeli - I forgot to mention, but please do remember to purge the old dev build. This essentially needs manually deleting the old folder from the gh-pages branch.

**Comment by RMeli** [comment]
I was actually going to open an issue to clarify this, since I saw there are also other previous *-dev builds. I'll remove them all then.

**Comment by IAlibay** [comment]
Thanks @RMeli . Removing them might make deployment issues less likely to happen too because the upload size will be way smaller.

**Comment by RMeli** [comment]
Done. But the old `*-dev` still appear under "Other versions" (and they are dangling links). Is there an easy way to remove them? Sorry for all the questions, but I've never touched the UserGuide deployment.

Edit: I searched for the old `*-dev` releases in the repo, but without any hit.

**Comment by IAlibay** [comment]
I think it might be in the sitemap metadata? It might be that the new sphinx theme has affected things though.
