### ISSUE TITLE
nbval errors on stderr output changes

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/UserGuide#357]
See: #356

FAILED polymer.ipynb::Cell 1
FAILED clustering_ensemble_similarity.ipynb::Cell 3
FAILED clustering_ensemble_similarity.ipynb::Cell 11
FAILED clustering_ensemble_similarity.ipynb::Cell 15
FAILED clustering_ensemble_similarity.ipynb::Cell 18
FAILED convergence.ipynb::Cell 2
FAILED convergence.ipynb::Cell 8
FAILED dimension_reduction_ensemble_similarity.ipynb::Cell 3
FAILED dimension_reduction_ensemble_similarity.ipynb::Cell 10
FAILED dimension_reduction_ensemble_similarity.ipynb::Cell 20
FAILED harmonic_ensemble_similarity.ipynb::Cell 3

**Comment by IAlibay** [comment]
Do we actually need to do a stderr check here? Could we just skip it completely?

**Comment by lilyminium** [comment]
Makes sense to me!

**Comment by IAlibay** [comment]
Very quick attempt at doing this in https://github.com/MDAnalysis/UserGuide/actions/runs/7388882737/job/20100603113?pr=358 doesn't seem to work. Someone might be better suited to take over here.
