### ISSUE TITLE
Recommend mamba over conda

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#361]
The user guide recommends conda -- I haven't been keeping up with its development but mamba still really seems the way to go instead.

**Comment by mikemhenry** [comment]
Yes, here is the latest https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html Miniforge is definitely the way to go in 2024.

**Comment by orbeckst** [comment]
Our [USer Guide installation instructions](https://userguide.mdanalysis.org/stable/installation.html#conda) recommend installing mamba _inside_ the mda env
```bash
conda create --name mdanalysis
conda activate mdanalysis
conda install -c conda-forge mamba
```
but this is **not recommended in the official mamba instructions** for [mamba with existing conda](https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html#existing-conda-install-not-recommended) where it is explicitly said 

> WARNING: Installing mamba into any other environment than `base` is not supported.

Therefore, we should also update the UG Installation Instructions.

**Comment by RMeli** [comment]
I agree with @mikemhenry. I've had a very smooth experience with Miniforge, from my laptop to HPC clusters. I think it would be best to suggest to use Miniforge directly.

**Comment by IAlibay** [comment]
Yeah we shouldn't be advocating for conda at all nowadays - it's blocked at most pharma companies.

**Comment by orbeckst** [comment]
I think we still need to mention "conda" because that's what people know who do not deal with the details of the python ecosystem, and it's even in the name "conda-forge".

**Comment by mikemhenry** [comment]
I think its fine to mention conda, then say mamba is a drop in replacement (so the same commands that worked with conda will work with mamba) is better, and the best way to install it is from Miniforge. Hopefully that isn't too much to overwhelm learners while still pointing them to the best solution

**Comment by jennaswa** [comment]
Hi all - thanks for your efforts and thoughts on this issue. What is the current status on updating the installation instructions in the User Guide? I'm wondering if this something we want to try to prioritize getting done before the UGM, especially so folks can reference it during the hackathon?

**Comment by orbeckst** [comment]
This looks like a "nice to have" for me – mamba/conda, potato/potatoe. If anyone feels strongly about it, please change it.

The much more pressing issue is updating installation instructions for develop #368 (EDIT: because we need them for the UGM!)
