### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/UserGuide#364]
CI has been consistently failing for a while with an MDAnalysisTests.topology import error. Looks like some kind of python environment error which I can't seem to be able to reproduce locally.

**Comment by RMeli** [comment]
Tanks @IAlibay, I've noticed this too and wasn't able to reproduce it either. But I didn't have much time to look at this. Hopefully I will have some soon.

**Comment by orbeckst** [comment]
Recent PRs (EDIT: such as https://github.com/MDAnalysis/UserGuide/pull/330 ) had all CI green — are you referring to an issue that's not obvious at the PR CI level?

**Comment by RMeli** [comment]
I think this issue has been fixed by https://github.com/MDAnalysis/UserGuide/pull/366.

**Comment by IAlibay** [comment]
This particular issue was fixed upstream - it was a packaging issue with the core library I had to resolve
