### ISSUE TITLE
Inconsistency in wildcard selection

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#37]
**Current documentation**
https://www.mdanalysis.org/UserGuide/selections.html#selection-keywords

<img width="554" alt="Screenshot 2020-01-04 at 8 52 47 AM" src="https://user-images.githubusercontent.com/31115101/71751420-96b87380-2ecf-11ea-91bf-61cc8416b782.png">

**Problem**
I think it would be better for the version "Note" information to be folded into the current dot point, which documents 0.20.1. The grammar could also be better, e.g. 

**From** version 0.21.0 **onwards**, MDAnalysis supports the use of *one* wildcard * at the start, middle, **or** end of strings. u.select_atoms("resname *E") will select **all** atoms **where the atom's** residue name ends in E.

**Comment by orbeckst** [comment]
This just changed with https://github.com/MDAnalysis/mdanalysis/issues/2436 – we now support fnmatch-based wildcards.

**Comment by orbeckst** [comment]
This is superseded by #55.

**Comment by orbeckst** [comment]
(If you want to update the old docs for pre 1.0 then re-open but I think that's low priority.)
