### ISSUE TITLE
Fix Dead Links in MDAnalysis User Guide Documentation

### ISSUE THREAD

**Issue by mhmohona** [MDAnalysis/UserGuide#393]
I checked [MDAnalysis User Guide - Stable Index](https://userguide.mdanalysis.org/stable/index.html) and found several links that are either broken, lead to 404 errors, or are inaccessible. Below is a table summarizing the problematic links, including the pages where they are found and the anchor text associated with them.

| **#** | **Error**       | **Anchor Text**         | **Linked From**                                               | **Broken Link**                                                                                  |
|-------|-----------------|-------------------------|---------------------------------------------------------------|--------------------------------------------------------------------------------------------------|
| 1     | 404 Not Found   | HOLE2 MDAKit            | [Releases](https://userguide.mdanalysis.org/stable/releases.html)  | [https://www.mdanalysis.org/hole2-mdakit/](https://www.mdanalysis.org/hole2-mdakit/)            |
| 2     | 404 Not Found   | @g2707                  | [Releases](https://userguide.mdanalysis.org/stable/releases.html)  | [https://github.com/g2707](https://github.com/g2707)                                            |
| 3     | 404 Not Found   | align_structure         | [Examples - README](https://userguide.mdanalysis.org/stable/examples/analysis/README.html) | [https://userguide.mdanalysis.org/examples/analysis/alignment_and_rms/aligning_structure_to_another.ipynb](https://userguide.mdanalysis.org/examples/analysis/alignment_and_rms/aligning_structure_to_another.ipynb) |
| 4     | 404 Not Found   | align_trajectory_first  | [Examples - README](https://userguide.mdanalysis.org/stable/examples/analysis/README.html) | [https://userguide.mdanalysis.org/examples/analysis/alignment_and_rms/aligning_trajectory_to_first_frame.ipynb](https://userguide.mdanalysis.org/examples/analysis/alignment_and_rms/aligning_trajectory_to_first_frame.ipynb) |
| 5     | 404 Not Found   | align_trajectory        | [Examples - README](https://userguide.mdanalysis.org/stable/examples/analysis/README.html) | [https://userguide.mdanalysis.org/examples/analysis/alignment_and_rms/aligning_trajectory.ipynb](https://userguide.mdanalysis.org/examples/analysis/alignment_and_rms/aligning_trajectory.ipynb) |
| 6     | 404 Not Found   | rmsf                    | [Examples - README](https://userguide.mdanalysis.org/stable/examples/analysis/README.html) | [https://userguide.mdanalysis.org/examples/analysis/alignment_and_rms/rmsf.ipynb](https://userguide.mdanalysis.org/examples/analysis/alignment_and_rms/rmsf.ipynb) |
| 7     | 404 Not Found   | Pydagogue               | [Contributing](https://userguide.mdanalysis.org/stable/contributing.html) | [https://matthew-brett.github.com/pydagogue/](https://matthew-brett.github.com/pydagogue/)       |
| 8     | 404 Not Found   | DataFrame               | [RMSD Analysis](https://userguide.mdanalysis.org/stable/examples/analysis/alignment_and_rms/rmsd.html) | [https://pandas.pydata.org/pandas-docs/stable/getting_started/dsintro.html](https://pandas.pydata.org/pandas-docs/stable/getting_started/dsintro.html) |
| 9     | -1 Not Found    | MMTF                    | [MMTF Format](https://userguide.mdanalysis.org/stable/formats/reference/mmtf.html) | [https://mmtf.rcsb.org/](https://mmtf.rcsb.org/)                                                |
| 10    | -1 Not Found    | HOOMD-blue              | [GSD Format](https://userguide.mdanalysis.org/stable/formats/reference/gsd.html) | [http://codeblue.umich.edu/hoomd-blue/index.html](http://codeblue.umich.edu/hoomd-blue/index.html) |
| 11    | -1 Not Found    | XML                     | [XML Format](https://userguide.mdanalysis.org/stable/formats/reference/xml.html) | [http://codeblue.umich.edu/hoomd-blue/doc/page_xml_file_format.html](http://codeblue.umich.edu/hoomd-blue/doc/page_xml_file_format.html) |
| 12    | -1 Not Found    | GAMESS-UK               | [GMS Format](https://userguide.mdanalysis.org/stable/formats/reference/gms.html) | [http://www.cfs.dl.ac.uk/](http://www.cfs.dl.ac.uk/)                                            |
| 13    | 404 Not Found   | MOL2                    | [MOL2 Format](https://userguide.mdanalysis.org/stable/formats/reference/mol2.html) | [http://chemyang.ccnu.edu.cn/ccb/server/AIMMS/mol2.pdf](http://chemyang.ccnu.edu.cn/ccb/server/AIMMS/mol2.pdf) |
| 14    | -1 Not Found    | FHI-aims                | [IN Format](https://userguide.mdanalysis.org/stable/formats/reference/in.html) | [https://aimsclub.fhi-berlin.mpg.de/](https://aimsclub.fhi-berlin.mpg.de/)                       |
| 15    | 404 Not Found   | PQR                     | [PQR Format](https://userguide.mdanalysis.org/stable/formats/reference/pqr.html) | [https://apbs-pdb2pqr.readthedocs.io/en/latest/formats/pqr.html](https://apbs-pdb2pqr.readthedocs.io/en/latest/formats/pqr.html) |
| 16    | 404 Not Found   | PDB2PQR                 | [PQR Format](https://userguide.mdanalysis.org/stable/formats/reference/pqr.html) | [https://apbs-pdb2pqr.readthedocs.io/en/latest/pdb2pqr/index.html](https://apbs-pdb2pqr.readthedocs.io/en/latest/pdb2pqr/index.html) |
| 17    | 404 Not Found   | APBS                    | [PQR Format](https://userguide.mdanalysis.org/stable/formats/reference/pqr.html) | [https://apbs-pdb2pqr.readthedocs.io/en/latest/apbs/index.html](https://apbs-pdb2pqr.readthedocs.io/en/latest/apbs/index.html) |
| 18    | -1 Not Found    | CRD                     | [CRD Format](https://userguide.mdanalysis.org/stable/formats/reference/crd.html) | [https://www.charmmtutorial.org/index.php/CHARMM:The_Basics](https://www.charmmtutorial.org/index.php/CHARMM:The_Basics) |
| 19    | 404 Not Found   | PARM                    | [TOP Format](https://userguide.mdanalysis.org/stable/formats/reference/top.html) | [https://ambermd.org/formats.html](https://ambermd.org/formats.html)                             |
| 20    | -1 Not Found    | IBIsCO                  | [TRZ Format](https://userguide.mdanalysis.org/stable/formats/reference/trz.html) | [http://www.theo.chemie.tu-darmstadt.de/ibisco/IBISCO.html](http://www.theo.chemie.tu-darmstadt.de/ibisco/IBISCO.html) |
| 21    | -1 Not Found    | YASP                    | [TRZ Format](https://userguide.mdanalysis.org/stable/formats/reference/trz.html) | [http://www.theo.chemie.tu-darmstadt.de/group/services/yaspdoc/yaspdoc.html](http://www.theo.chemie.tu-darmstadt.de/group/services/yaspdoc/yaspdoc.html) |
                    
I am ready to start working on fixing these issues, but I would appreciate some feedback or suggestions before proceeding. Also, if there are preferred sources to replace outdated links, please provide them.

**Comment by RMeli** [comment]
@mhmohona that is fantastic investigative work, thank you for doing this. I think it would be great to fix the broken links for sure. Tracking down the new links with Google is probably the best course of action; the old link should give you already quite a bit of information.

For example, Googling 
```
hole2-mdakit
```
the first hit is the GitHub repository of `mdahole2`, while the second hit is already the link we want: https://mdakits.mdanalysis.org/mdahole2.html (i.e. a link to the official MDAnalysis MDAKit repository for the hole2 MDAKit).

**Comment by mhmohona** [comment]
I wasn't able to fix the broken links in https://userguide.mdanalysis.org/stable/formats/format_reference.html because I couldn't find the correct links for row number 11 through 21.

**Comment by RMeli** [comment]
Hi @mhmohona, what have you tried in these cases? 11 through 21 seems to be linked to specific file formats of different software. Have you looked into the documentation of said software? The most likely cause of the link breakage is that the page about the file format has moved within the documentation of the software (or that the documentation of the software has moved all together).
