### ISSUE TITLE
Analysis (general)

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#4]
**Story:** *As a* user, *I want* to know how whether the analysis I have in mind is already implemented, how to use it, and how to possibly implement it myself, *so that* I can make contributions to science.

**Acceptance criteria:**

- [x] I know where to find a list of accepted MD formats, and the information that each format provides.
- [x] I know where to find whether an analysis requires particular information that may not be in every MD format (e.g. masses). 
- [x] I know where to find a list of available analyses.
- [x] I know where to find a tutorial on implementing custom analysis.
- [x] I understand the general interface for running analysis.

**Comment by richardjgowers** [comment]
discussion on the Analysis interface:

https://github.com/MDAnalysis/mdanalysis/issues/719

**Comment by orbeckst** [comment]
And the current problem that the docs are missing AtomGroup methods that require masses, see https://github.com/MDAnalysis/mdanalysis/issues/1845

**Comment by orbeckst** [comment]
I would also add: the docs point to the primary literature and I know how to read about the implemented method.

Ultimately I would also need to know how to cite a certain existing analysis. The [duecredit functionality](https://www.mdanalysis.org/docs/documentation_pages/references.html#id12) might be worthwhile pointing out.

**Comment by orbeckst** [comment]
IMO, this issue seems to be the place to lead towards `AnalysisBase`, and not so much #7

**Comment by lilyminium** [comment]
@richardjgowers Are there any plans to refactor existing modules e.g. `helanal` and `gnm` to fit the Bauhaus style?

@orbeckst MDAnalysis gives my coarse-grained beads masses of 0 when it can't guess them from a GRO file -- is this behaviour common to all formats, or is the `mass` attribute simply missing from some of them?

**Comment by richardjgowers** [comment]
I'm not sure there's a rule re: guessing masses. 0 is a good compromise for failure (though maybe np.NaN might be better?) because it's obviously not right.  Sentinel values like 1 could seem correct?

**Comment by lilyminium** [comment]
Oops, sorry for the edit, I’m on my phone and thought I was replying — reverted back. 

> I'm not sure there's a rule re: guessing masses. 0 is a good compromise for failure (though maybe np.NaN might be better?) because it's obviously not right.  Sentinel values like 1 could seem correct?


np.NaN strikes me as better because I suppose virtual sites or dummy atoms would have a mass of 0. Also, I think it might fail in mass-related calculations, which is probably desirable?

**Comment by orbeckst** [comment]
The user guide allows people to find analysis tools (and now we also have mdakits).
