### ISSUE TITLE
Move MDAnalysis cookbook examples to tutorials

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#49]
**Is your feature request related to a problem? Please describe.**
[The examples in the cookbook](https://github.com/MDAnalysis/MDAnalysisCookbook/tree/master/examples) are useful but likely out of date.

**Describe the solution you'd like**
Add Jupyter tutorials with modern code.

**Comment by orbeckst** [comment]
They are _really_ out of date, so let's not bother.
