### ISSUE TITLE
Building topology attributes

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#5]
**Story:** *As a* user, *I want* to add bfactors to my PDB, *so that* I can visualise my analysis. [Notebook example]

**Story:** *As a* user, *I want* to populate my Universe with custom atom properties, *so that* I can generate desired molecules from coordinate arrays. 

**Acceptance criteria:**

- [x] I understand that most topology manipulation is done through Universe.
- [x] I understand how to add and modify topology attributes.
- [x] I know the limited attributes that can be added and what they correspond to (e.g. temp factors = bfactors)
- [x] I know how to write out a single frame

Related to #3

**Comment by lilyminium** [comment]
```ValueError: Unrecognised topology attribute name: 'random'.  Possible values: 'altLoc, altLocs, angles, atomattr, atomattrs, atomiccharge, atomiccharges, atomnum, atomnums, bfactor, bfactors, bonds, chainID, chainIDs, charge, charges, dihedrals, element, elements, icode, icodes, id, ids, impropers, index, indices, mass, masses, model, models, molnum, molnums, moltype, moltypes, name, names, occupancies, occupancy, radii, radius, record_type, record_types, resid, resids, residueattr, residueattrs, resindex, resindices, resname, resnames, resnum, resnums, segid, segids, segindex, segindices, segmentattr, segmentattrs, tempfactor, tempfactors, topologyattr, topologyattrs, type, type_index, type_indices, types'```

**Comment by richardjgowers** [comment]
The error message is interesting, maybe good error messages are a form of documentation?

Also tempfactors == bfactors can/should be squashed/aliased together:

https://github.com/MDAnalysis/mdanalysis/issues/1901

**Comment by orbeckst** [comment]
This is a [FAQ](https://github.com/MDAnalysis/mdanalysis/wiki/FAQ) – unfortunately, it is not **in** the FAQ...

**Comment by lilyminium** [comment]
Closed by #30
