### ISSUE TITLE
Unformatted *

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/UserGuide#56]
**Describe the bug**

In the [Quickstart-RMSD](https://www.mdanalysis.org/UserGuide/examples/quickstart.html#RMSD) there area few `*`. Their intent is not  clear to me.

**To Reproduce**
1. Go to  [Quickstart-RMSD](https://www.mdanalysis.org/UserGuide/examples/quickstart.html#RMSD)
2. Scroll down to `Below, the RMSD class is created.` (paragraph 4)

**Expected behavior**

I'm not entirely sure what is the intent of `*` here. 

**Actual behavior**

No  `*` or text formatted differently?

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox 
 - Version: 73

**Comment by zemanj** [comment]
Looks like it's supposed
* to be a list
* with bullet points?
