### ISSUE TITLE
AtomGroup methods

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#7]
**Story:** *As a* user, *I want* to compute domain angles, *so that* I can track conformational rearrangements of domains.

**Acceptance criteria:**

- [x] I know the available AtomGroup methods, e.g. center_of_geometry
- [x] I understand that many of these require masses
- [x] I know how to subclass AnalysisBase to automate this

**Comment by orbeckst** [comment]
I am not sure if `AnalysisBase` fits in here. I'd rather say that the next step in any simple analysis is to ask if you can modularize it and then we get into "write new analysis tools based on the Analysis API".

**Comment by orbeckst** [comment]
In general, knowing AtomGroup methods and attributes is one of the most important things to learn because you need `positions` for pretty much anything, and many of the existing methods make life a lot easier.

**Comment by lilyminium** [comment]
> I am not sure if `AnalysisBase` fits in here. I'd rather say that the next step in any simple analysis is to ask if you can modularize it and then we get into "write new analysis tools based on the Analysis API".

Yeah, that sounds good. It's probably unlikely that the everyday user would rather subclass AnalysisBase than simply change the filenames in their script.

**Comment by lilyminium** [comment]
I think the spirit of this issue has been closed, if not the exact user story.
