### ISSUE TITLE
Segmentation fault when building the user guide

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#82]
**Describe the bug**

Both RTD and Travis segmentation fault when building the user guide here:

```
reading sources... [ 98%] trajectories/transformations
Segmentation fault (core dumped)
```

Locally it works.

**To Reproduce**
1. Open a PR

**Symptoms**

- Pinning all the package versions did not fix it
- Just after reading all the sources, there are many warnings. Could these be related? 
```
UserGuide/doc/source/datasets.rst:6: WARNING: Duplicate explicit target name: "mdanalysisdata".
source/examples/analysis/alignment_and_rms/README.rst:18: WARNING: toctree contains reference to nonexisting document 'examples/analysis/alignment_and_rms/aligning_trajectory_to_first_frame'
source/examples/analysis/alignment_and_rms/README.rst:7: WARNING: duplicate label alignment-and-rms, other instance in UserGuide/doc/source/examples/analysis/alignment_and_rms/README.rst
source/examples/analysis/trajectory_similarity/README.rst:6: WARNING: duplicate label trajectory-similarity, other instance in UserGuide/doc/source/examples/analysis/trajectory_similarity/README.rst
UserGuide/doc/source/examples/analysis/alignment_and_rms/README.rst:18: WARNING: toctree contains reference to nonexisting document 'examples/analysis/alignment_and_rms/aligning_trajectory_to_first_frame'
UserGuide/doc/source/examples/analysis/alignment_and_rms/README.rst:7: WARNING: duplicate label alignment-and-rms, other instance in UserGuide/doc/source/examples/analysis/README.rst
UserGuide/doc/source/examples/analysis/trajectory_similarity/README.rst:6: WARNING: duplicate label trajectory-similarity, other instance in UserGuide/doc/source/examples/analysis/README.rst
UserGuide/doc/source/formats/coordinates.rst:4: WARNING: duplicate label coordinate-readers, other instance in UserGuide/doc/source/formats/index.rst
source/formats/coordinates.rst:4: WARNING: duplicate label coordinate-readers, other instance in UserGuide/doc/source/formats/coordinates.rst
UserGuide/doc/source/formats/reference/trj.rst:35: WARNING: Bullet list ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... UserGuide/doc/source/examples/analysis/alignment_and_rms/aligning_trajectory_to_frame.ipynb: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [ 10%] examples/analysis/alignment_and_rms/aligning_structure_writing output... [ 12%] examples/analysis/alignment_and_rms/aligning_trajectorywriting output... [ 13%] examples/analysis/alignment_and_rms/pairwise_rmsd    writing output... [100%] universe                                               le_similarity_similarity
UserGuide/doc/source/contributing_code.rst:7: WARNING: undefined label: https://github.com/mdanalysis/mdanalysis/pulls (if the link has no caption the label must precede a section header)
UserGuide/doc/source/contributing_code.rst:21: WARNING: undefined label: writing new code (if the link has no caption the label must precede a section header)
UserGuide/doc/source/installation.rst:96: WARNING: undefined label: mdanalysisdata (if the link has no caption the label must precede a section header)
```

**Desktop (please complete the following information):**
- Which version of MDAnalysis? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
- Which version of Python (`python -V`)?

**Smartphone (please complete the following information):**

**Additional context**

**Comment by IAlibay** [comment]
As requested off-list, I tried this locally and I can't reproduce it either.

**Comment by lilyminium** [comment]
https://travis-ci.com/github/MDAnalysis/UserGuide/builds/173576019 It works without the trajectories/ directory.

**Comment by lilyminium** [comment]
Binary search has the problem definitely somewhere in this bit of code:

```python
u = mda.Universe(TPR, XTC)
protein = u.select_atoms('protein')
align_transform = trans.fit_rot_trans(protein, protein, weights='mass')
u.trajectory.add_transformations(align_transform)
```

**Comment by lilyminium** [comment]
It's specific to the `trans.fit_rot_trans` function when called (i.e. `trans.fit_rot_trans(ts)`).

**Comment by lilyminium** [comment]
A couple avenues we could take here:

* actually debug this thing properly by running Travis locally in a Docker container. There might be an actual bug in here somewhere. This requires non-negligible effort.
* give up and just write normal code blocks instead of having `ipython` run an actual Python interpreter. The docs *do* build locally on mine and @IAlibay's systems, and the code runs fine in a conda environment created from `environment.yml`.

I've been testing out various lines of code in #83.

**Comment by lilyminium** [comment]
As @IAlibay noted elsewhere, this seems to be happening due to something in the `align` module in the main code. In order to keep the user guide moving forward I'll fix this in the short term by switching the transformations document to non-interpreted Python code (tomorrow, unless someone else wants to do it) until the main problem is found and fixed.

**Comment by IAlibay** [comment]
Update here, on my own test package, I can replicate the failures seen here, but MDA's Travis doesn't: https://github.com/MDAnalysis/mdanalysis/pull/2819

It seems very clear that there's something up with XTC files here, but that it's somehow related to either a) a difference in how Travis is set up here and MDA, or b) some difference between the MDA develop package and what's on the conda-forge channel.
